version: "2"

run:
  tests: true

formatters:
  enable:
    - gofmt
    - goimports

linters:
  default: none
  enable:
    - errcheck
    - gosec
    - govet
    - ineffassign
    - revive
    - staticcheck
    - unused
